import { describe, it, expect } from 'vitest'
import { isGeneratedPath, hasGeneratedMarker, isGeneratedFile } from './generated'

describe('isGeneratedPath — lockfiles', () => {
  const lockfiles = [
    'package-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
    'Cargo.lock',
    'poetry.lock',
    'Gemfile.lock',
    'composer.lock',
    'go.sum',
    'sub/dir/pnpm-lock.yaml', // nested still matches by basename
  ]
  for (const f of lockfiles) {
    it(`flags lockfile ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — minified / map', () => {
  const cases = ['app.min.js', 'styles.min.css', 'bundle.js.map', 'styles.css.map', 'source.map']
  for (const f of cases) {
    it(`flags ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — protobuf stubs', () => {
  const cases = ['user.pb.go', 'user.pb.cc', 'user.pb.h', 'user_pb2.py', 'user_pb2.pyi', 'user_pb.js', 'user_pb.d.ts']
  for (const f of cases) {
    it(`flags ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — generated infixes', () => {
  const cases = ['api.generated.ts', 'model.gen.go', 'Form.designer.cs']
  for (const f of cases) {
    it(`flags ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — swagger/openapi', () => {
  const cases = ['swagger.json', 'openapi.yaml', 'api.openapi.json', 'service-swagger.yml']
  for (const f of cases) {
    it(`flags ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — generated directory segments', () => {
  const cases = [
    'src/generated/types.ts',
    'GENERATED/x.ts', // case-insensitive
    'app/__generated__/graphql.ts',
    'proto/gen/service.ts',
    'dist/bundle.js',
    'src/dist/index.js',
    'pkg/generated/api/client.ts', // mid-path
  ]
  for (const f of cases) {
    it(`flags ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(true)
    })
  }
})

describe('isGeneratedPath — snapshots', () => {
  it('flags a .snap file', () => {
    expect(isGeneratedPath('src/__snapshots__/Button.test.tsx.snap')).toBe(true)
  })
  it('flags anything under __snapshots__', () => {
    expect(isGeneratedPath('test/__snapshots__/x')).toBe(true)
  })
  it('flags a bare .snap extension outside the dir', () => {
    expect(isGeneratedPath('weird/place/foo.snap')).toBe(true)
  })
})

describe('isGeneratedPath — conservative negatives (hand-written files)', () => {
  const handWritten = [
    'src/index.ts',
    'src/generator.ts', // "gen" prefix in BASENAME, not a dir segment
    'src/regenerate/util.ts', // dir CONTAINS "gen" but isn't the segment
    'src/codegen.ts', // basename contains "gen"
    'src/types.d.ts', // hand-written ambient decls NOT in a generated dir
    'src/genuine/thing.ts', // segment starts with "gen" but isn't exactly "gen"
    'README.md',
    'docs/openapi-guide.md', // mentions openapi but not the generated spec file
    'src/distance.ts', // basename contains "dist" but no dist segment
    'src/components/Button.svelte',
  ]
  for (const f of handWritten) {
    it(`does NOT flag ${f}`, () => {
      expect(isGeneratedPath(f)).toBe(false)
    })
  }
  it('returns false for empty path', () => {
    expect(isGeneratedPath('')).toBe(false)
  })
})

describe('hasGeneratedMarker — content markers', () => {
  it('detects @generated', () => {
    expect(hasGeneratedMarker('// @generated by tool\nexport const x = 1')).toBe(true)
  })
  it('detects Go-style "Code generated … DO NOT EDIT."', () => {
    expect(hasGeneratedMarker('// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x')).toBe(true)
  })
  it('detects a bare generated + DO NOT EDIT banner', () => {
    expect(hasGeneratedMarker('/* This file is generated.\n   DO NOT EDIT it. */')).toBe(true)
  })
  it('is case-insensitive', () => {
    expect(hasGeneratedMarker('// @GENERATED')).toBe(true)
  })
  it('does NOT flag a hand-written file mentioning generated casually', () => {
    expect(hasGeneratedMarker('// This function returns a generated id\nfunction id() {}')).toBe(false)
  })
  it('does NOT scan past the first ~40 lines', () => {
    const body = Array(50).fill('const x = 1').join('\n') + '\n// @generated'
    expect(hasGeneratedMarker(body)).toBe(false)
  })
  it('returns false for null/empty', () => {
    expect(hasGeneratedMarker(null)).toBe(false)
    expect(hasGeneratedMarker('')).toBe(false)
  })
})

describe('isGeneratedFile — combined path + content', () => {
  it('flags by path even without contents', () => {
    expect(isGeneratedFile('pnpm-lock.yaml')).toBe(true)
  })
  it('flags by content marker when path is innocuous', () => {
    expect(
      isGeneratedFile('src/api.ts', { before: null, after: '// @generated\nexport const x = 1' }),
    ).toBe(true)
  })
  it('falls back to before-content for deletions', () => {
    expect(
      isGeneratedFile('src/api.ts', { before: '// @generated\nexport const x = 1', after: null }),
    ).toBe(true)
  })
  it('does NOT flag a normal file with normal contents', () => {
    expect(
      isGeneratedFile('src/index.ts', { before: null, after: 'export const x = 1' }),
    ).toBe(false)
  })
})
