/**
 * Model catalog — the per-provider MODEL LIST, extracted from providers.ts so a
 * sync script (scripts/sync-models.mts) can regenerate it deterministically
 * against OpenRouter's public models API.
 *
 * This file is the SINGLE SOURCE OF TRUTH for model ids / labels / context
 * windows / pricing / tool-support. providers.ts wires each provider's `models`
 * from MODEL_CATALOG[id] and authors everything else (id, displayName,
 * transport, baseUrl, defaultModel, keyHint, maxTokensParam) itself — those
 * provider-level fields NEVER live here and are out of scope for the sync.
 *
 * Human-readable TS (not JSON) on purpose: the typing and the pricing-source /
 * deprecation comments are load-bearing context. The sync script rewrites this
 * file from a computed catalog when upstream drifts; hand-edited comments on
 * existing entries are NOT preserved across an automated rewrite.
 *
 * AUTO-GENERATED region: the MODEL_CATALOG below is regenerated by
 * scripts/sync-models.mts. Prefer editing via that script. The `openrouter`
 * lineup is the FULL generated list (openrouterCatalog.generated.ts), imported
 * here so this stays the single pricing source for every selectable model.
 */

import type { LlmModelDef, LlmProviderId } from './providers'
import { OPENROUTER_MODELS } from './openrouterCatalog.generated'

export const MODEL_CATALOG: Record<LlmProviderId, LlmModelDef[]> = {
  deepseek: [
    { id: "deepseek-v4-flash", label: "DeepSeek V4 Flash", contextWindowTokens: 1000000, pricing: { inputPer1M: 0.0811, outputPer1M: 0.1621 } },
    { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro", contextWindowTokens: 1000000, pricing: { inputPer1M: 0.7078, outputPer1M: 1.4157 } },
    { id: "deepseek-chat", label: "DeepSeek Chat (legacy)", contextWindowTokens: 1000000, pricing: { inputPer1M: 0.32, outputPer1M: 0.89 } },
    { id: "deepseek-reasoner", label: "DeepSeek Reasoner (legacy)", contextWindowTokens: 1000000, supportsTools: false, pricing: { inputPer1M: 0.2002, outputPer1M: 0.8001 } },
    { id: "deepseek-v4-flash-vision-exp", label: "Deepseek v4 Flash Vision Exp", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.22, outputPer1M: 0.66 } },
    { id: "deepseek-v4-pro-0813", label: "Deepseek v4 Pro 0813", contextWindowTokens: 1048576, pricing: { inputPer1M: 1.1207, outputPer1M: 3.362 } },
    { id: "deepseek-v4-flash-0731", label: "Deepseek v4 Flash 0731", contextWindowTokens: 1310720, pricing: { inputPer1M: 0.05, outputPer1M: 0.1 } },
  ],
  openai: [
    { id: "gpt-5.5", label: "GPT-5.5", contextWindowTokens: 1000000, pricing: { inputPer1M: 5, outputPer1M: 30 } },
    { id: "gpt-5.4", label: "GPT-5.4", contextWindowTokens: 1000000, pricing: { inputPer1M: 2.5, outputPer1M: 15 } },
    { id: "gpt-5.4-mini", label: "GPT-5.4 mini", contextWindowTokens: 400000, pricing: { inputPer1M: 0.75, outputPer1M: 4.5 } },
    { id: "gpt-5.2", label: "GPT-5.2", contextWindowTokens: 400000, pricing: { inputPer1M: 1.75, outputPer1M: 14 } },
    { id: "gpt-6-astra", label: "Gpt 6 Astra", contextWindowTokens: 1050000, pricing: { inputPer1M: 10, outputPer1M: 50 } },
    { id: "gpt-6-astra-pro", label: "Gpt 6 Astra Pro", contextWindowTokens: 1050000, pricing: { inputPer1M: 10, outputPer1M: 50 } },
    { id: "gpt-5.6-luna-pro", label: "Gpt 5.6 Luna Pro", contextWindowTokens: 1050000, pricing: { inputPer1M: 0.2, outputPer1M: 1.2 } },
    { id: "gpt-5.6-luna", label: "Gpt 5.6 Luna", contextWindowTokens: 1050000, pricing: { inputPer1M: 0.2, outputPer1M: 1.2 } },
    { id: "gpt-5.6-terra-pro", label: "Gpt 5.6 Terra Pro", contextWindowTokens: 1050000, pricing: { inputPer1M: 2, outputPer1M: 12 } },
    { id: "gpt-5.6-terra", label: "Gpt 5.6 Terra", contextWindowTokens: 1050000, pricing: { inputPer1M: 2, outputPer1M: 12 } },
    { id: "gpt-5.6-sol-pro", label: "Gpt 5.6 Sol Pro", contextWindowTokens: 1050000, pricing: { inputPer1M: 2, outputPer1M: 10 } },
    { id: "gpt-5.6-sol", label: "Gpt 5.6 Sol", contextWindowTokens: 1050000, pricing: { inputPer1M: 2, outputPer1M: 10 } },
  ],
  anthropic: [
    { id: "claude-fable-5", label: "Claude Fable 5", contextWindowTokens: 1000000, pricing: { inputPer1M: 10, outputPer1M: 50 } },
    { id: "claude-opus-4-8", label: "Claude Opus 4.8", contextWindowTokens: 1000000, pricing: { inputPer1M: 5, outputPer1M: 25 } },
    { id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6", contextWindowTokens: 1000000, pricing: { inputPer1M: 3, outputPer1M: 15 } },
    { id: "claude-haiku-4-5", label: "Claude Haiku 4.5", contextWindowTokens: 200000, pricing: { inputPer1M: 1, outputPer1M: 5 } },
    { id: "claude-fable-5.1", label: "Claude Fable 5.1", contextWindowTokens: 1000000, pricing: { inputPer1M: 10, outputPer1M: 50 } },
    { id: "claude-opus-5", label: "Claude Opus 5", contextWindowTokens: 1000000, pricing: { inputPer1M: 5, outputPer1M: 25 } },
  ],
  gemini: [
    { id: "gemini-3.5-flash", label: "Gemini 3.5 Flash", contextWindowTokens: 1048576, pricing: { inputPer1M: 1.5, outputPer1M: 9 } },
    { id: "gemini-3.1-pro-preview", label: "Gemini 3.1 Pro (preview)", contextWindowTokens: 1048576, pricing: { inputPer1M: 2, outputPer1M: 12 } },
    { id: "gemini-2.5-flash", label: "Gemini 2.5 Flash", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.3, outputPer1M: 2.5 } },
    { id: "gemini-2.5-pro", label: "Gemini 2.5 Pro", contextWindowTokens: 1048576, pricing: { inputPer1M: 1.25, outputPer1M: 10 } },
    { id: "gemini-3.8-flash", label: "Gemini 3.8 Flash", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.75, outputPer1M: 3.75 } },
    { id: "gemini-3.7-flash", label: "Gemini 3.7 Flash", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.75, outputPer1M: 3.75 } },
    { id: "gemini-3.6-flash", label: "Gemini 3.6 Flash", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.75, outputPer1M: 3.75 } },
    { id: "gemini-3.5-flash-lite", label: "Gemini 3.5 Flash Lite", contextWindowTokens: 1048576, pricing: { inputPer1M: 0.3, outputPer1M: 2.5 } },
  ],
  openrouter: OPENROUTER_MODELS,
}
