/**
 * src/lib/guide/triage.test.ts — mechanical-vs-novel triage + risk-first order.
 *
 * Covers every mechanical signal, the findings/high-risk override (a flagged
 * file is NEVER mechanical), the reason chip labels, the version-bump-only
 * detector's conservatism, and the deterministic risk-first ordering.
 */
import { describe, it, expect } from 'vitest'
import type { PrFile } from '../github/types'
import type { RiskFinding } from '../risk/risk'
import { classifyFile, isVersionBumpOnly, sortRiskFirst, pathCompare } from './triage'

const PATCH = '@@ -1 +1 @@\n-old\n+new'

function makeFile(filename: string, overrides: Partial<PrFile> = {}): PrFile {
  return { filename, status: 'modified', additions: 1, deletions: 0, patch: PATCH, ...overrides }
}

const NO_FINDINGS: RiskFinding[] = []
const ONE_FINDING: RiskFinding[] = [{ severity: 'medium' }]

// ---------------------------------------------------------------------------
// Mechanical signals
// ---------------------------------------------------------------------------

describe('classifyFile — mechanical signals', () => {
  it('generated file (path signal) → mechanical, reason "generated"', () => {
    const t = classifyFile(makeFile('src/__generated__/api.ts'), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toContain('generated')
  })

  it('generated file (content marker) → mechanical when contents are loaded', () => {
    const contents = { before: null, after: '// @generated by protoc\nexport const x = 1\n' }
    const t = classifyFile(makeFile('src/api_stub.ts'), 'low', NO_FINDINGS, contents)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['generated'])
  })

  it('lockfile → mechanical with the specific "lockfile" label (not just "generated")', () => {
    const t = classifyFile(makeFile('pnpm-lock.yaml'), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['lockfile'])
  })

  it('snapshot artifact → mechanical with the "snapshot" label', () => {
    const t = classifyFile(makeFile('src/__snapshots__/render.snap'), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toContain('snapshot')
  })

  it('tests-only file → mechanical, reason "tests only"', () => {
    const t = classifyFile(makeFile('src/lib/foo.test.ts'), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['tests only'])
  })

  it('rename without content changes → mechanical, reason "rename only"', () => {
    const t = classifyFile(
      makeFile('src/renamed.ts', { status: 'renamed', additions: 0, deletions: 0, patch: undefined, previousFilename: 'src/old.ts' }),
      'low',
      NO_FINDINGS,
    )
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['rename only'])
  })

  it('rename WITH content changes is NOT mechanical', () => {
    const t = classifyFile(makeFile('src/renamed.ts', { status: 'renamed', additions: 3, deletions: 1 }), 'low', NO_FINDINGS)
    expect(t.attention).toBe('novel')
    expect(t.reasons).toEqual([])
  })

  it('manifest version-bump-only → mechanical, reason "version bumps"', () => {
    const patch = '@@ -1,2 +1,2 @@\n-  "chalk": "^4.1.2",\n+  "chalk": "^5.0.0",\n   "left-pad": "1.3.0"'
    const t = classifyFile(makeFile('package.json', { patch }), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['version bumps'])
  })

  it('manifest adding a NEW dependency is NOT mechanical', () => {
    const patch = '@@ -1,1 +1,2 @@\n   "chalk": "^5.0.0",\n+  "left-pad": "1.3.0",'
    const t = classifyFile(makeFile('package.json', { patch }), 'low', NO_FINDINGS)
    expect(t.attention).toBe('novel')
    expect(t.reasons).toEqual([])
  })

  it('a plain source change is novel with no reasons', () => {
    const t = classifyFile(makeFile('src/app.ts'), 'medium', NO_FINDINGS)
    expect(t).toEqual({ attention: 'novel', reasons: [] })
  })

  it('collects EVERY matching signal (snapshot in a test-named file)', () => {
    const t = classifyFile(makeFile('src/__snapshots__/render.test.ts.snap'), 'low', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
    expect(t.reasons).toEqual(['snapshot', 'tests only'])
  })
})

// ---------------------------------------------------------------------------
// Findings / high-risk override — never bury a flagged file
// ---------------------------------------------------------------------------

describe('classifyFile — findings/risk override', () => {
  it('a generated file carrying a finding is NEVER mechanical', () => {
    const t = classifyFile(makeFile('src/__generated__/api.ts'), 'low', ONE_FINDING)
    expect(t.attention).toBe('novel')
    // Reasons stay reported — truthful shape data; attention decides the tail.
    expect(t.reasons).toContain('generated')
  })

  it('a tests-only file carrying a finding is NEVER mechanical', () => {
    const t = classifyFile(makeFile('src/lib/foo.test.ts'), 'low', ONE_FINDING)
    expect(t.attention).toBe('novel')
  })

  it('a lockfile with HIGH file-risk is NEVER mechanical', () => {
    const t = classifyFile(makeFile('pnpm-lock.yaml'), 'high', NO_FINDINGS)
    expect(t.attention).toBe('novel')
    expect(t.reasons).toEqual(['lockfile'])
  })

  it('medium risk does NOT override a mechanical shape (only high does)', () => {
    const t = classifyFile(makeFile('pnpm-lock.yaml'), 'medium', NO_FINDINGS)
    expect(t.attention).toBe('mechanical')
  })
})

// ---------------------------------------------------------------------------
// isVersionBumpOnly — conservative by construction
// ---------------------------------------------------------------------------

describe('isVersionBumpOnly', () => {
  it('true for a pure version bump (added line pairs with a removed twin)', () => {
    expect(isVersionBumpOnly('@@ -1 +1 @@\n-  "chalk": "^4.1.2",\n+  "chalk": "^5.0.0",')).toBe(true)
  })

  it('true for go.mod-style bumps', () => {
    expect(isVersionBumpOnly('@@ -1 +1 @@\n-require example.com/mod v1.2.3\n+require example.com/mod v1.3.0')).toBe(true)
  })

  it('false when a genuinely new line appears (no removed counterpart)', () => {
    expect(isVersionBumpOnly('@@ -1 +1,2 @@\n-  "chalk": "^4.1.2",\n+  "chalk": "^5.0.0",\n+  "left-pad": "1.3.0",')).toBe(false)
  })

  it('false when the range operator changed (not a pure bump shape)', () => {
    expect(isVersionBumpOnly('@@ -1 +1 @@\n-  "chalk": "^4.1.2",\n+  "chalk": "~5.0.0",')).toBe(false)
  })

  it('false for pure removals (removing a dep is a real change)', () => {
    expect(isVersionBumpOnly('@@ -1,2 +1 @@\n-  "left-pad": "1.3.0",\n   "chalk": "^5.0.0"')).toBe(false)
  })

  it('false for an absent patch (unverifiable)', () => {
    expect(isVersionBumpOnly(undefined)).toBe(false)
  })

  it('multiset matching: two identical bumped lines need two removed twins', () => {
    // One removed "x": "1.0.0" cannot license TWO added "x": "2.0.0" lines.
    expect(isVersionBumpOnly('@@ -1 +1,2 @@\n-  "x": "1.0.0",\n+  "x": "2.0.0",\n+  "x": "2.0.0",')).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// sortRiskFirst — deterministic, highest first, path tie-break
// ---------------------------------------------------------------------------

describe('sortRiskFirst', () => {
  const riskOf = (f: PrFile) =>
    f.filename.startsWith('high/') ? ('high' as const) : f.filename.startsWith('med/') ? ('medium' as const) : ('low' as const)

  it('orders high → medium → low with a path tie-break inside each band', () => {
    const files = [
      makeFile('low/z.ts'),
      makeFile('med/b.ts'),
      makeFile('high/y.ts'),
      makeFile('high/a.ts'),
      makeFile('med/a.ts'),
      makeFile('low/a.ts'),
    ]
    const sorted = sortRiskFirst(files, riskOf).map((f) => f.filename)
    expect(sorted).toEqual(['high/a.ts', 'high/y.ts', 'med/a.ts', 'med/b.ts', 'low/a.ts', 'low/z.ts'])
  })

  it('is deterministic regardless of input order', () => {
    const a = [makeFile('med/a.ts'), makeFile('high/a.ts'), makeFile('low/a.ts')]
    const b = [makeFile('low/a.ts'), makeFile('med/a.ts'), makeFile('high/a.ts')]
    expect(sortRiskFirst(a, riskOf).map((f) => f.filename)).toEqual(sortRiskFirst(b, riskOf).map((f) => f.filename))
  })

  it('returns a new array and never mutates the input', () => {
    const files = [makeFile('low/z.ts'), makeFile('high/a.ts')]
    const before = files.map((f) => f.filename)
    sortRiskFirst(files, riskOf)
    expect(files.map((f) => f.filename)).toEqual(before)
  })
})

describe('pathCompare', () => {
  it('is a plain deterministic code-unit compare', () => {
    expect(pathCompare('a', 'b')).toBe(-1)
    expect(pathCompare('b', 'a')).toBe(1)
    expect(pathCompare('a', 'a')).toBe(0)
  })
})
